"""er_store_purchase_unique

Revision ID: 12affbf632e2
Revises: d535d962984f
Create Date: 2026-09-30 22:50:07.875903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '12affbf632e2'
down_revision: Union[str, None] = 'd535d962984f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('StorePurchase_userId_itemId_key', 'StorePurchase', ['userId', 'itemId'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('StorePurchase_userId_itemId_key', 'StorePurchase', type_='unique')
    # ### end Alembic commands ###
