"""er_initial_schema

Revision ID: d535d962984f
Revises: 
Create Date: 2026-09-30 16:10:46.866762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd535d962984f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('StoreItem',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=16), nullable=False),
    sa.Column('icon', sa.String(length=64), nullable=False),
    sa.Column('imageUrl', sa.Text(), nullable=True),
    sa.Column('effect', sa.String(length=64), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_StoreItem_category', 'StoreItem', ['category'], unique=False)
    op.create_table('User',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('passwordHash', sa.String(length=255), nullable=True),
    sa.Column('provider', sa.String(length=64), nullable=True),
    sa.Column('providerAccountId', sa.String(length=255), nullable=True),
    sa.Column('resetToken', sa.String(length=255), nullable=True),
    sa.Column('resetTokenExpiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fullName', sa.String(length=255), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('avatar', sa.Text(), nullable=True),
    sa.Column('banner', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('profession', sa.String(length=255), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('birthDate', sa.DateTime(timezone=True), nullable=True),
    sa.Column('socialLinks', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('isGuest', sa.Boolean(), nullable=False),
    sa.Column('isPrivate', sa.Boolean(), nullable=False),
    sa.Column('twoFAEnabled', sa.Boolean(), nullable=False),
    sa.Column('tourCompleted', sa.Boolean(), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('lastSeen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('devCoins', sa.Integer(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('AccountDeletionCode',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('userId', sa.String(length=40), nullable=False),
    sa.Column('codeHash', sa.String(length=255), nullable=False),
    sa.Column('expiresAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed', sa.Boolean(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_AccountDeletionCode_userId', 'AccountDeletionCode', ['userId'], unique=False)
    op.create_table('Block',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('blockerId', sa.String(length=40), nullable=False),
    sa.Column('blockedId', sa.String(length=40), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['blockedId'], ['User.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['blockerId'], ['User.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_Block_blockedId', 'Block', ['blockedId'], unique=False)
    op.create_index('ix_Block_blockerId', 'Block', ['blockerId'], unique=False)
    op.create_table('ChatMessage',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('userId', sa.String(length=40), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ChatMessage_createdAt', 'ChatMessage', ['createdAt'], unique=False)
    op.create_table('DevCoinTransaction',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('userId', sa.String(length=40), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_DevCoinTransaction_userId', 'DevCoinTransaction', ['userId'], unique=False)
    op.create_table('DirectMessage',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('senderId', sa.String(length=40), nullable=False),
    sa.Column('recipientId', sa.String(length=40), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('readAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recipientId'], ['User.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['senderId'], ['User.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_DirectMessage_createdAt', 'DirectMessage', ['createdAt'], unique=False)
    op.create_index('ix_DirectMessage_recipientId_readAt', 'DirectMessage', ['recipientId', 'readAt'], unique=False)
    op.create_index('ix_DirectMessage_senderId_recipientId', 'DirectMessage', ['senderId', 'recipientId'], unique=False)
    op.create_table('Follow',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('followerId', sa.String(length=40), nullable=False),
    sa.Column('followeeId', sa.String(length=40), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['followeeId'], ['User.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['followerId'], ['User.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_Follow_followeeId', 'Follow', ['followeeId'], unique=False)
    op.create_index('ix_Follow_followerId', 'Follow', ['followerId'], unique=False)
    op.create_table('LoginCode',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('userId', sa.String(length=40), nullable=False),
    sa.Column('codeHash', sa.String(length=255), nullable=False),
    sa.Column('expiresAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('usedAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_LoginCode_userId_createdAt', 'LoginCode', ['userId', 'createdAt'], unique=False)
    op.create_table('LoginEvent',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('userId', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('userAgent', sa.String(length=512), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_LoginEvent_createdAt', 'LoginEvent', ['createdAt'], unique=False)
    op.create_index('ix_LoginEvent_userId', 'LoginEvent', ['userId'], unique=False)
    op.create_table('Notification',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('userId', sa.String(length=40), nullable=False),
    sa.Column('fromUserId', sa.String(length=40), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('entityId', sa.String(length=40), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fromUserId'], ['User.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_Notification_read', 'Notification', ['read'], unique=False)
    op.create_index('ix_Notification_userId', 'Notification', ['userId'], unique=False)
    op.create_table('Post',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('authorId', sa.String(length=40), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('mediaUrls', sa.Text(), nullable=True),
    sa.Column('repostOfId', sa.String(length=40), nullable=True),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['authorId'], ['User.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repostOfId'], ['Post.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_Post_authorId', 'Post', ['authorId'], unique=False)
    op.create_index('ix_Post_createdAt', 'Post', ['createdAt'], unique=False)
    op.create_index('ix_Post_repostOfId', 'Post', ['repostOfId'], unique=False)
    op.create_index('ix_Post_type', 'Post', ['type'], unique=False)
    op.create_table('Report',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('reporterId', sa.String(length=40), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('entityId', sa.String(length=40), nullable=False),
    sa.Column('reason', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reporterId'], ['User.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_Report_reporterId', 'Report', ['reporterId'], unique=False)
    op.create_index('ix_Report_status', 'Report', ['status'], unique=False)
    op.create_table('StorePurchase',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('userId', sa.String(length=40), nullable=False),
    sa.Column('itemId', sa.String(length=40), nullable=False),
    sa.Column('pricePaid', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['itemId'], ['StoreItem.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_StorePurchase_userId', 'StorePurchase', ['userId'], unique=False)
    op.create_table('Beta',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('postId', sa.String(length=40), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('downloadType', sa.String(length=16), nullable=False),
    sa.Column('fileUrl', sa.Text(), nullable=True),
    sa.Column('fileSize', sa.Integer(), nullable=True),
    sa.Column('fileName', sa.Text(), nullable=True),
    sa.Column('externalUrl', sa.Text(), nullable=True),
    sa.Column('betaStatus', sa.String(length=32), nullable=False),
    sa.Column('genre', sa.String(length=64), nullable=True),
    sa.Column('version', sa.String(length=32), nullable=True),
    sa.Column('platforms', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('requirements', sa.Text(), nullable=True),
    sa.Column('changelog', sa.Text(), nullable=True),
    sa.Column('installInstructions', sa.Text(), nullable=True),
    sa.Column('coverImage', sa.Text(), nullable=True),
    sa.Column('screenshots', sa.Text(), nullable=True),
    sa.Column('externalPlatform', sa.String(length=64), nullable=True),
    sa.Column('downloads', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['postId'], ['Post.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('postId')
    )
    op.create_index('ix_Beta_postId', 'Beta', ['postId'], unique=False)
    op.create_table('Bookmark',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('postId', sa.String(length=40), nullable=False),
    sa.Column('userId', sa.String(length=40), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['postId'], ['Post.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_Bookmark_postId', 'Bookmark', ['postId'], unique=False)
    op.create_index('ix_Bookmark_userId', 'Bookmark', ['userId'], unique=False)
    op.create_table('Comment',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('postId', sa.String(length=40), nullable=False),
    sa.Column('userId', sa.String(length=40), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['postId'], ['Post.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_Comment_postId', 'Comment', ['postId'], unique=False)
    op.create_index('ix_Comment_userId', 'Comment', ['userId'], unique=False)
    op.create_table('Like',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('postId', sa.String(length=40), nullable=False),
    sa.Column('userId', sa.String(length=40), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['postId'], ['Post.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_Like_postId', 'Like', ['postId'], unique=False)
    op.create_index('ix_Like_userId', 'Like', ['userId'], unique=False)
    op.create_table('Poll',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('postId', sa.String(length=40), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('allowMultiple', sa.Boolean(), nullable=False),
    sa.Column('closesAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['postId'], ['Post.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('postId')
    )
    op.create_index('ix_Poll_postId', 'Poll', ['postId'], unique=False)
    op.create_table('Stream',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('userId', sa.String(length=40), nullable=False),
    sa.Column('postId', sa.String(length=40), nullable=True),
    sa.Column('platform', sa.String(length=16), nullable=False),
    sa.Column('streamUrl', sa.Text(), nullable=False),
    sa.Column('embedUrl', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('isLive', sa.Boolean(), nullable=False),
    sa.Column('startedAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('endedAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['postId'], ['Post.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('postId')
    )
    op.create_index('ix_Stream_isLive', 'Stream', ['isLive'], unique=False)
    op.create_index('ix_Stream_userId', 'Stream', ['userId'], unique=False)
    op.create_table('PollOption',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('pollId', sa.String(length=40), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('voteCount', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pollId'], ['Poll.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_PollOption_pollId', 'PollOption', ['pollId'], unique=False)
    op.create_table('PollVote',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('pollId', sa.String(length=40), nullable=False),
    sa.Column('optionId', sa.String(length=40), nullable=False),
    sa.Column('userId', sa.String(length=40), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['optionId'], ['PollOption.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pollId'], ['Poll.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_PollVote_pollId', 'PollVote', ['pollId'], unique=False)
    op.create_index('ix_PollVote_userId', 'PollVote', ['userId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_PollVote_userId', table_name='PollVote')
    op.drop_index('ix_PollVote_pollId', table_name='PollVote')
    op.drop_table('PollVote')
    op.drop_index('ix_PollOption_pollId', table_name='PollOption')
    op.drop_table('PollOption')
    op.drop_index('ix_Stream_userId', table_name='Stream')
    op.drop_index('ix_Stream_isLive', table_name='Stream')
    op.drop_table('Stream')
    op.drop_index('ix_Poll_postId', table_name='Poll')
    op.drop_table('Poll')
    op.drop_index('ix_Like_userId', table_name='Like')
    op.drop_index('ix_Like_postId', table_name='Like')
    op.drop_table('Like')
    op.drop_index('ix_Comment_userId', table_name='Comment')
    op.drop_index('ix_Comment_postId', table_name='Comment')
    op.drop_table('Comment')
    op.drop_index('ix_Bookmark_userId', table_name='Bookmark')
    op.drop_index('ix_Bookmark_postId', table_name='Bookmark')
    op.drop_table('Bookmark')
    op.drop_index('ix_Beta_postId', table_name='Beta')
    op.drop_table('Beta')
    op.drop_index('ix_StorePurchase_userId', table_name='StorePurchase')
    op.drop_table('StorePurchase')
    op.drop_index('ix_Report_status', table_name='Report')
    op.drop_index('ix_Report_reporterId', table_name='Report')
    op.drop_table('Report')
    op.drop_index('ix_Post_type', table_name='Post')
    op.drop_index('ix_Post_repostOfId', table_name='Post')
    op.drop_index('ix_Post_createdAt', table_name='Post')
    op.drop_index('ix_Post_authorId', table_name='Post')
    op.drop_table('Post')
    op.drop_index('ix_Notification_userId', table_name='Notification')
    op.drop_index('ix_Notification_read', table_name='Notification')
    op.drop_table('Notification')
    op.drop_index('ix_LoginEvent_userId', table_name='LoginEvent')
    op.drop_index('ix_LoginEvent_createdAt', table_name='LoginEvent')
    op.drop_table('LoginEvent')
    op.drop_index('ix_LoginCode_userId_createdAt', table_name='LoginCode')
    op.drop_table('LoginCode')
    op.drop_index('ix_Follow_followerId', table_name='Follow')
    op.drop_index('ix_Follow_followeeId', table_name='Follow')
    op.drop_table('Follow')
    op.drop_index('ix_DirectMessage_senderId_recipientId', table_name='DirectMessage')
    op.drop_index('ix_DirectMessage_recipientId_readAt', table_name='DirectMessage')
    op.drop_index('ix_DirectMessage_createdAt', table_name='DirectMessage')
    op.drop_table('DirectMessage')
    op.drop_index('ix_DevCoinTransaction_userId', table_name='DevCoinTransaction')
    op.drop_table('DevCoinTransaction')
    op.drop_index('ix_ChatMessage_createdAt', table_name='ChatMessage')
    op.drop_table('ChatMessage')
    op.drop_index('ix_Block_blockerId', table_name='Block')
    op.drop_index('ix_Block_blockedId', table_name='Block')
    op.drop_table('Block')
    op.drop_index('ix_AccountDeletionCode_userId', table_name='AccountDeletionCode')
    op.drop_table('AccountDeletionCode')
    op.drop_table('User')
    op.drop_index('ix_StoreItem_category', table_name='StoreItem')
    op.drop_table('StoreItem')
    # ### end Alembic commands ###
